spring.application.name=ex25-branch

server.port=8090

# ======================================
# MariaDB
# ======================================
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=2356

# ======================================
# MyBatis >> 데이터베이스와의 상호작용
# SQL 매핑: XML 파일에 SQL 질의를 정의하거나, @을 사용하여 SQL을 자바 메소드와 직접 연결
# ======================================
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.lej.ex25_branch.domain
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# ======================================
# Encoding
# ======================================
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.force-request=true
server.servlet.encoding.force-response=true

# ======================================
# Logging
# ======================================
logging.level.root=info
logging.level.com.lej.ex25_branch.service=debug
logging.level.com.lej.ex25_branch.mapper=DEBUG

# ======================================
# thymeleaf >> 뷰 템플릿 엔진
# 템플릿 렌더링: HTML, XML 등의 문서를 동적으로 생성하여 클라이언트에게 응답
# ======================================
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false